import { apiSlice } from "./apiSlice";
import { STUDENT_URL } from "../constants"; // Ensure this is correct for your environment

export const studentApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Fetch all students
    getStudents: builder.query({
      query: () => ({
        url: `${STUDENT_URL}`,
        method: "GET",
      }),
    }),

    // Add a new student
    addStudent: builder.mutation({
      query: (studentData) => ({
        url: `${STUDENT_URL}`,
        method: "POST",
        body: studentData,
      }),
    }),

    // Update student data
    updateStudent: builder.mutation({
      query: ({ id, studentData }) => ({
        url: `${STUDENT_URL}/${id}`,
        method: "PUT",
        body: studentData,
      }),
    }),

    // Delete a student
    deleteStudent: builder.mutation({
      query: (id) => ({
        url: `${STUDENT_URL}/${id}`,
        method: "DELETE",
      }),
    }),

    // save engagement result
    saveEngagementResult: builder.mutation({
      query: ({
        rollNo,
        finalEngagementStatus,
        engagementCategory,
        engagementPercentage,
      }) => {
        const payload = {
          rollNo,
          finalEngagementStatus,
          engagementCategory,
          engagementPercentage,
        };

        console.log("Payload being sent to backend:", payload); // Debugging log

        return {
          url: `${STUDENT_URL}/engagement`,
          method: "POST",
          body: payload,
        };
      },
    }),
  }),
});

// Export hooks generated by the slice
export const {
  useGetStudentsQuery,
  useAddStudentMutation,
  useUpdateStudentMutation,
  useDeleteStudentMutation,
  useSaveEngagementResultMutation,
} = studentApiSlice;
